language: go
go:
  - 1.5.1
before_install:
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/golang/lint/golint
  - go get golang.org/x/tools/cmd/vet
install:
  - go list ./... | grep -v examples | go get
before_script:
  # vet the code...fail build if error
  - go vet ./...
script:
  - go get github.com/aristanetworks/goeapi
  - make -j4 test GOTEST_FLAGS=-v
after_success:
  - make coveragefunc
